// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwrrforhndpinxatxqda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cnJmb3JobmRwaW54YXR4cWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjQ0MjAsImV4cCI6MjA2MzUwMDQyMH0.zTeIm3kFWfHKPotKBZ0cUaFn0N38hRFnQCj7hl43eM4";

// Use service role key if available (bypasses RLS), otherwise use anon key
const SUPABASE_SERVICE_ROLE_KEY = "eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cnJmb3JobmRwaW54YXR4cWRhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzkyNDQyMCwiZXhwIjoyMDYzNTAwNDIwfQ"
const SUPABASE_KEY = SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;

if (SUPABASE_SERVICE_ROLE_KEY) {
  console.log("🔑 Using Supabase Service Role Key (RLS bypassed)");
} else {
  console.log("⚠️ Using Anon Key - you may encounter RLS permission errors");
  console.log("💡 To fix: Add VITE_SUPABASE_SERVICE_ROLE_KEY to .env.local");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});