// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwrrforhndpinxatxqda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cnJmb3JobmRwaW54YXR4cWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjQ0MjAsImV4cCI6MjA2MzUwMDQyMH0.zTeIm3kFWfHKPotKBZ0cUaFn0N38hRFnQCj7hl43eM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});